import I18nProvider from "@/provider/i18n/I18nProvider";
import ThemeRegistry from "@/provider/theme/ThemeRegistry";
import { MainLayout } from "@/template";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/logo/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ThemeRegistry>
          <I18nProvider>
            <MainLayout>{children}</MainLayout>
          </I18nProvider>
        </ThemeRegistry>
      </body>
    </html>
  );
}
